@startuml UML

class Roupas{
    - id: long
    - quantidade: Integer
    - valor: Float
    - cor: String
    - tipoDeTercido: String
    - marca: String
    - modelo: String
    - Cliente: Cliente

    + GetSet()


}
class Cliente{
    -id: long
    - cpf: String
    - nome: String
    - localEntrega: LocalEntrega

    + GetSet()
}

class LocalEntrega{
    - id: long
    - cep: String
    - enderecoCompleto: String
    - complemento: String
    - referencia: String

    + GetSet()
}
class ItemCompra {
    - id: Long
    - quantidade: Integer
    - preco: Double
}
class Compra {
    - id: Long
    - data: Date
    - totalCompra: Double
}
class Telefone {
    - id: Long
    - codigoArea: String
    - numero: String
}
    LocalEntrega "*" <--*"1" Cliente

    Cliente "*" --> "*" Roupas: listaDesejo

    Compra "1" *--> "*" ItemCompra
    Compra "*" --> "1" Cliente
    Compra "*"  --> "1" LocalEntrega

    ItemCompra "*" --> "1" Roupas

    Cliente "1" *--> "1" Telefone: celular
    Cliente "1" *--> "1" Telefone: whatszap
@enduml
